version: "3.9"

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.dev

    command: npm run dev

    volumes:
      - .:/usr/src/app

    environment:
      - POSTGRES_URL=postgresql://dashboard:turboPassword123@db/dashboard
      - POSTGRES_URL_NON_POOLING=postgresql://dashboard:turboPassword123@db/dashboard

    ports:
      - 3000:3000
    
    depends_on:
      - db



  db:
    image: postgres:16

    environment:
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=turboPassword123

    ports:
      - 5432:5432
